import { MainProvider } from "@/context/MainContext";
import "@/styles/global.css";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Şikayet var",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
        </Head>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
